# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Pro Max",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (12.9-inch) (2nd generation)"
])

languages([
  "en-US",
  "es-419"
])

# The name of the scheme which contains the UI Tests
scheme("QuickPersonalFinanceUITests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-snapshot"])

# Retries
number_of_retries(0)

# Headless
headless(false)

# Dark mode
dark_mode(false)

# For more information about all available options run
# fastlane action snapshot
