# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 14 Pro Max",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)",
  "iPad Pro (12.9-inch) (2nd generation)"
])

languages([
  "en-US",
  "es-419"
])

# The name of the scheme which contains the UI Tests
scheme("QuickPersonalFinanceUITests")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# The number of times a test can fail before snapshot should stop retrying
number_of_retries(0)

# Enabling this option will prevent displaying the simulator window
headless(false)

# Enabling this option will configure the Simulator to be in dark mode (false for light, true for dark)
dark_mode(false)

# Enabling this option will configure the Simulator's system language
localize_simulator(true) # not working

# Take snapshots on multiple simulators concurrently. Note: This option is only applicable when running against Xcode 9
concurrent_simulators(false)

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
# override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-snapshot"])

# For more information about all available options run
# fastlane action snapshot
